### ISSUE TITLE
False fail?

### ISSUE THREAD

**Issue by dennisholmer** [trilogy-group/eng-standard#4]
According to the run, the branch is not review protected, but it is? Am I doing something wrong?

![image](https://user-images.githubusercontent.com/1439413/142919178-dae08402-fc6e-41a7-94d7-37146f7fce36.png)

![image](https://user-images.githubusercontent.com/1439413/142919305-466e450c-9657-43fb-bc2e-eac1bad4cb6e.png)

**Comment by dennisholmer** [comment]
@Tantalon Maybe you can shed some light on this? :)

**Comment by Tantalon** [comment]
Hi @dennisholmer, this may mean that the @trilogy-eng-standards user does not have admin access to the repo. GitHub hides some information in the API responses if access is lower.

**Comment by dennisholmer** [comment]
Yes! That was it, it was only set to be a writer, thanks @Tantalon !
