### ISSUE TITLE
Main branch protection check does not work

### ISSUE THREAD

**Issue by dishang-trilogy** [trilogy-group/eng-standard#6]
Failing check for protected main branch even though it is already setup
https://github.com/trilogy-group/eng-standard/blob/main/src/rules/Reviewing.ts#L25

Repo: https://github.com/trilogy-group/devflows-jsonata-extension
![image](https://user-images.githubusercontent.com/70003612/145205027-626f0244-56c7-4e08-8135-8996eb13e798.png)
![image](https://user-images.githubusercontent.com/70003612/145205095-22e0095f-760f-408a-85db-14bf02191780.png)

**Comment by Tantalon** [comment]
See https://github.com/trilogy-group/eng-standard/issues/4
